<?php

$htmlString = "<div id=\"element\" class = 'page-main' data-mage-init='{\"accordion\":{\"openedState\": \"active\", \"collapsible\": true, \"active\": false, \"multipleCollapsible\": true}}'>";
$html = '';
$htmlCloseDiv = '</div>';

$storeCollection = $this->getStorelocatorCollection();
$province = null;

$productCollection = $this->getStorelocatorCollection();


foreach ($productCollection as $product) {
    echo "<br>";
    print_r($product->getData());
    echo "<br>";
}


foreach ($storeCollection as $store) {
   if($province == null){
       $province = $store["province"];

       $html .= '<div style="border:1px solid black; data-role="collapsible">';
       $html .= '<div data-role="trigger">';
       $html .= '<span>'.$store["province"].'</span>';
       $html .= '<div  data-role="content">'.$store['name'].'</div>';

   }elseif($province == $store["province"] ){
        $html .= '<div  data-role="content">'.$store['name'].'</div>';
    }else{
        $province = $store["province"];

       $html .= $htmlCloseDiv;
       $html .= $htmlCloseDiv;

        $html .= '<div style="border:1px solid black; data-role="collapsible">';
        $html .= '<div data-role="trigger">';
        $html .= '<span>'.$store["province"].'</span>';
        $html .= '<div data-role="content">'.$store['name'].'</div>';


   }

    $htmlString .= $html;
    $html = '';
}
    $htmlString .= $htmlCloseDiv;
    $htmlString .= $htmlCloseDiv;

    echo $htmlString;
?>
